<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getPostsGroupedByYear() {
        $qb = $this->createQueryBuilder('p');

        $qb->select('YEAR(p.createdAt) as yearPublished,
                        COUNT(p.id) as numberOfPosts ')
            ->groupBy('yearPublished');

        return $qb->getQuery()->getArrayResult();
    }
}
